# Generated by Django 5.0.1 on 2024-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_bid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='remaining_time',
            field=models.IntegerField(),
        ),
    ]
