# Generated by Django 5.0.1 on 2024-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0002_remove_product_category_remove_product_initial_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_highest_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_remaining_time',
            field=models.IntegerField(default=20),
        ),
    ]
