# Generated by Django 5.0.1 on 2024-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0003_remove_product_image_product_price_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='forBot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='forPeople',
            field=models.BooleanField(default=False),
        ),
    ]
