# Generated by Django 5.0.1 on 2024-04-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0004_product_forbot_product_forpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
    ]
