# Generated by Django 5.0.1 on 2024-04-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0005_product_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bids_count',
            field=models.IntegerField(default=0),
        ),
    ]
