# Generated by Django 5.0.1 on 2024-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0006_product_bids_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='highest_bid',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='remaining_time',
            field=models.IntegerField(null=True),
        ),
    ]
