# Generated by Django 5.0.1 on 2024-04-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0007_alter_product_bid_alter_product_highest_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='condition',
        ),
    ]
