# Generated by Django 5.0.1 on 2024-04-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0008_rename_description_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='increment',
            field=models.IntegerField(default=0),
        ),
    ]
