# Generated by Django 5.0.1 on 2024-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0009_product_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
