# Generated by Django 5.0.1 on 2024-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0010_alter_product_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
