# Generated by Django 5.0.1 on 2024-04-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0011_alter_product_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_bid',
            field=models.IntegerField(default=0),
        ),
    ]
