# Generated by Django 5.0.1 on 2024-04-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_app', '0012_product_initial_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bids_count',
        ),
    ]
